move action to local

diff --git a/.github/workflows/build-lint-test.yaml b/.github/workflows/build-lint-test.yaml
--- a/.github/workflows/build-lint-test.yaml
+++ b/.github/workflows/build-lint-test.yaml
@@ -1,6 +1,121 @@
 name: "Build Test Lint"
-on: [ push, pull_request]
-jobs: 
-  call-workflow:
-    uses: scientist-softserv/build-lint-test-action/.github/workflows/build-test-lint.yaml@blacklight
-  
+on: [ pull_request ]
+
+env:
+  REGISTRY: ghcr.io
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set env
+        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+      - name: Github Container Login
+        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Pull from cache to speed up build
+        run: >-
+          touch .env.development;
+          TAG=latest docker-compose pull web || true
+      - name: Build and push
+        uses: docker/build-push-action@v3
+        with:
+          platforms: linux/amd64,linux/arm64
+          cache-from: |
+            ${{ env.REGISTRY }}/${{ github.repository }}:${TAG}
+          push: true
+          tags: |
+            ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG }}
+      
+  lint:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set env
+        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Github Container Login
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Pull from cache to speed up build
+        run: >-
+          touch .env.development;
+          docker-compose pull web;
+          docker-compose pull worker
+      - name: Run Rubocop
+        run: docker-compose run web bundle exec rubocop --parallel --format progress --format junit --out rubocop.xml --display-only-failed
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: 'rubocop*.xml'
+
+  test:
+    needs: build
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        # Set N number of parallel jobs you want to run tests on.
+        # Use higher number if you have slow tests to split them on more parallel jobs.
+        # Remember to update ci_node_index below to 0..N-1
+        ci_node_total: [3]
+        # set N-1 indexes for parallel jobs
+        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
+        ci_node_index: [0, 1, 2]
+    env:
+      ALLOW_ANONYMOUS_LOGIN: "yes"
+      CONFDIR: "/app/samvera/hyrax-webapp/solr/config"
+      DB_CLEANER_ALLOW_REMOTE_DB_URL: "true"
+      TB_RSPEC_FORMATTER: progress
+      TB_RSPEC_OPTIONS: --format RspecJunitFormatter --out rspec.xml
+    steps:
+      - name: Set env
+        run: echo "TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
+        # run: echo "TAG=f9867d90" >> $GITHUB_ENV
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Github Container Login
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ env.REGISTRY }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Pull from cache to speed up build
+        run: >-
+          touch .env.development;
+          docker-compose pull web;
+      - name: Start containers
+        run: docker-compose up -d web
+      - name: Setup db
+        run: >-
+          docker-compose exec -T web bash -c
+          "RAILS_ENV=test bundle exec rake db:schema:load db:migrate db:seed"
+      - name: Setup tmate session
+        uses: mxschmitt/action-tmate@v3
+        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
+        with:
+          limit-access-to-actor: true
+      - name: Run Specs
+        continue-on-error: true
+        run: >-
+          docker-compose exec -T web bash -c
+          "bundle exec rspec"
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: 'rspec*.xml'
